# Generated by Django 4.2.7 on 2026-02-24 13:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEthicsPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('rules', models.JSONField(default=dict, help_text='Policy rules in JSON format')),
                ('max_daily_usage', models.IntegerField(default=100, help_text='Maximum AI interactions per day', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_weekly_usage', models.IntegerField(default=500, help_text='Maximum AI interactions per week', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Ethics Policy',
                'verbose_name_plural': 'AI Ethics Policies',
                'db_table': 'ai_ethics_policy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_tool', models.CharField(choices=[('chatgpt', 'ChatGPT'), ('copilot', 'GitHub Copilot'), ('claude', 'Claude'), ('gemini', 'Google Gemini'), ('other', 'Other AI Tool')], max_length=50)),
                ('usage_type', models.CharField(choices=[('code_generation', 'Code Generation'), ('code_explanation', 'Code Explanation'), ('debugging', 'Debugging Assistance'), ('documentation', 'Documentation'), ('learning', 'Learning/Tutorial'), ('research', 'Research'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='Brief description of what was done')),
                ('course_code', models.CharField(blank=True, max_length=50)),
                ('assignment_id', models.CharField(blank=True, max_length=50)),
                ('duration_minutes', models.IntegerField(default=0, help_text='Duration of AI tool usage in minutes', validators=[django.core.validators.MinValueValidator(0)])),
                ('tokens_used', models.IntegerField(default=0, help_text='Approximate tokens/API calls used', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_compliant', models.BooleanField(default=True)),
                ('compliance_notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='dashboard.aiethicspolicy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Usage Log',
                'verbose_name_plural': 'AI Usage Logs',
                'db_table': 'ai_usage_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('data_collection_consent', models.BooleanField(default=False)),
                ('consent_date', models.DateTimeField(blank=True, null=True)),
                ('allow_analytics', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('weekly_summary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('usage_pattern', 'Usage Pattern'), ('compliance', 'Compliance'), ('recommendation', 'Recommendation'), ('achievement', 'Achievement'), ('warning', 'Warning')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('data', models.JSONField(default=dict, help_text='Additional data for the insight (charts, metrics, etc.)')),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('related_usage_logs', models.ManyToManyField(blank=True, related_name='insights', to='dashboard.aiusagelog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Insight',
                'verbose_name_plural': 'User Insights',
                'db_table': 'user_insight',
                'ordering': ['-priority', '-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('bug', 'Bug Report'), ('feature', 'Feature Request'), ('improvement', 'Improvement Suggestion'), ('general', 'General Feedback')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True, help_text='URL where issue occurred')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='feedback_screenshots/')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Under Review'), ('planned', 'Planned'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('admin_response', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Feedback',
                'verbose_name_plural': 'User Feedback',
                'db_table': 'user_feedback',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_level', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('warning', 'Warning'), ('violation', 'Violation')], max_length=20)),
                ('compliance_score', models.IntegerField(help_text='Compliance score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_usage_count', models.IntegerField(default=0)),
                ('compliant_usage_count', models.IntegerField(default=0)),
                ('violation_count', models.IntegerField(default=0)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_statuses', to='dashboard.aiethicspolicy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Status',
                'verbose_name_plural': 'Compliance Statuses',
                'db_table': 'compliance_status',
                'ordering': ['-calculated_at'],
                'unique_together': {('user', 'policy', 'period_start')},
            },
        ),
        migrations.AddIndex(
            model_name='aiusagelog',
            index=models.Index(fields=['user', '-timestamp'], name='ai_usage_lo_user_id_48fed7_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusagelog',
            index=models.Index(fields=['timestamp'], name='ai_usage_lo_timesta_aaedc1_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusagelog',
            index=models.Index(fields=['ai_tool'], name='ai_usage_lo_ai_tool_e7b733_idx'),
        ),
    ]
